# Generated by Django 4.1.3 on 2022-12-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
